services:
  dj:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./dj:/dj
    # depends_on:
    #   - db
    environment:
      - DJANGO_SETTINGS_MODULE=dj.settings
    networks:
      - mynet

  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - dj
    networks:
      - mynet

  # db:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_USER: <your_db_user>
  #     POSTGRES_PASSWORD: <your_db_password>
  #     POSTGRES_DB: <your_db_name>
  #   networks:
  #     - mynet

networks:
  mynet: