services:
  dj:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./dj:/dj
    # depends_on:
    #   - db
    environment:
      - DJANGO_SETTINGS_MODULE=dj.settings
    networks:
      - mynet
    deploy:
      resources:
        limits:   # check parser - Theres a two day limit on keys
          cpus: '1'  # Limit to 0.5 CPU cores
          # Keys limit of 2days exists at source of creation. This memory limit is arbitrary.
          memory: '800m'
    restart: unless-stopped

  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - dj
    networks:
      - mynet
    deploy:
      resources:
        limits:   # check parser - Theres a two day limit on keys
          cpus: '0.5'  # Limit to 0.5 CPU cores
          # Keys limit of 2days exists at source of creation. This memory limit is arbitrary.
          memory: '64m'
    restart: unless-stopped

  # db:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_USER: <your_db_user>
  #     POSTGRES_PASSWORD: <your_db_password>
  #     POSTGRES_DB: <your_db_name>
  #   networks:
  #     - mynet

networks:
  mynet: